export const FETCH_APPS = "FETCH_APPS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_APPS_BY_CATEGORY = "FETCH_APPS_BY_CATEGORY";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const FETCH_TOTAL_RECORDS = "FETCH_TOTAL_RECORDS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
